
server:
  port: 8080

logging:
  level:
    com.example.darpan.portfolio_practice: DEBUG
    ORG.springframework.web: INFO
    org.hibernate.SQL: DEBUG

cors:
  allowed-origin:
    - http://locahost:8080
    - http://localhost:5173

spring:
  application:
    name: portfolio-practice

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  profiles:
    active: prod



